apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-stable
  labels:
    usage: stable
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: web-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-canary
  labels:
    usage: stable
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: web-nginx
