apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: webcheck
spec:
  # args:
  # - name: host
  metrics:
  - name: webcheck
    failureLimit: 1
    interval: 5
    successCondition: result == "ok"
    provider:
      web:
        # paceholders are resolved when an AnalysisRun is created
        url: "http://{{args.host}}/"
        jsonPath: "{$.status}"
# kind: AnalysisTemplate
# apiVersion: argoproj.io/v1alpha1
# metadata:
#   name: canary-check
# spec:
#   metrics:
#   - name: test
#     provider:
#       job:
#         spec:
#           backoffLimit: 1
#           template:
#             spec:
#               containers:
#               - name: busybox
#                 image: busybox
#                 #args: [test]  #--> for making analysis fail, uncomment
#               restartPolicy: Never
