# apiVersion: argoproj.io/v1alpha1
# kind: AnalysisTemplate
# metadata:
#   name: canary-check
# spec:
#   args:
#   - name: host
#   metrics:
#   - name: canary-check
#     successCondition: result <= 0.05
#     interval: 30s
#     initialDelay: 30s
#     provider:
#       web:
#         url: "http://{{args.host}}/"
#         timeoutSeconds: 20
#         jsonPath: "{$.error_rate}"
########################
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-check
spec:
  args:
  - name: host
  metrics:
  - name: canary-check
    failureLimit: 1
    interval: 1
    successCondition: result == "ok"
    provider:
      web:
        # paceholders are resolved when an AnalysisRun is created
        url: "http://{{args.host}}/"
        # url: "http://34.100.195.123"
        jsonPath: "{$.status}"
################
###############################################################
# apiVersion: argoproj.io/v1alpha1
# kind: AnalysisTemplate
# metadata:
#   name: canary-check
# spec:
#   # env:
#   # - name: host
#   metrics:
#   - name: canary-check
#     # successCondition: result <= 0.05
#     # interval: 30s
#     # initialDelay: 30s
#     failureLimit: 1
#     interval: 5
#     successCondition: result == "ok"
#     provider:
#       web:
#         # paceholders are resolved when an AnalysisRun is created
#         url: "http://34.100.142.44:8080/"
#         # url: "http://{{env.host}}/"
#         timeoutSeconds: 20
#         jsonPath: "{$.status}"

#####################################
# kind: AnalysisTemplate
# apiVersion: argoproj.io/v1alpha1
# metadata:
#   name: canary-check
# spec:
#   metrics:
#   - name: test
#     provider:
#       job:
#         spec:
#           backoffLimit: 1
#           template:
#             spec:
#               containers:
#               - name: busybox
#                 image: busybox
#                 #args: [test]  #--> for making analysis fail, uncomment
#               restartPolicy: Never


##########################################
# apiVersion: argoproj.io/v1alpha1
# kind: AnalysisTemplate
# metadata:
#   name: canary-check
# spec:
#   args:
#   - name: host
#   metrics:
#   - name: canary-check
#     successCondition: result <= 0.05
#     interval: 30s
#     initialDelay: 30s
#     # failureLimit: 1
#     # interval: 5
#     # successCondition: result == "ok"
#     provider:
#       web:
#         # paceholders are resolved when an AnalysisRun is created
#         url: "http://{{args.host}}/"
#         timeoutSeconds: 20
#         jsonPath: "{$.status}"

#########################################

# kind: AnalysisTemplate
# apiVersion: argoproj.io/v1alpha1
# metadata:
#   name: canary-check
# spec:
#   metrics:
#   - name: test
#     provider:
#       job:
#         spec:
#           backoffLimit: 1
#           template:
#             spec:
#               containers:
#               - name: busybox
#                 image: busybox
#                 #args: [test]  #--> for making analysis fail, uncomment
#               restartPolicy: Never
